# Generated by Django 3.2.16 on 2022-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
