# Generated by Django 3.2.16 on 2022-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_on_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_auther',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='on_deal',
            field=models.BooleanField(default=False),
        ),
    ]
