# Generated by Django 3.2.16 on 2022-12-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20221205_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
